namespace MidiMinuit.Music.Core
{
    public enum IntervalAlias
    {
        PerfectUnison,
        PerfectFourth,
        PerfectFifth,
        PerfectOctave,
        MajorSecond,
        MajorThird,
        MajorSixth,
        MajorSeventh,
        MinorSecond,
        MinorThird,
        MinorSixth,
        MinorSeventh,
        AugmentedUnison,
        AugmentedSecond,
        AugmentedThird,
        AugmentedFourth,
        AugmentedFifth,
        AugmentedSixth,
        AugmentedSeventh,
        AugmentedOctave,
        DiminishedSecond,
        DiminishedThird,
        DiminishedFourth,
        DiminishedFifth,
        DiminishedSixth,
        DiminishedSeventh,
        DiminishedOctave,
        MajorNinth,
        AugmentedEleventh
    }
}