namespace MidiMinuit.Lib.Chords.Tools.Enum
{
    public enum Role
    {
        NoteFondamental,
        NoteSecondMinor,
        NoteSecondMajor,
        NoteSecondAugmented,
        NoteThirdMinor,
        NoteThirdMajor,
        NoteFourthPerfect,
        NoteFourthAugmented,
        NoteFifthDiminished,
        NoteFifthPerfect,
        NoteFifthAugmented,
        NoteSixthMinor,
        NoteSixthMajor,
        NoteSeventhDiminished,
        NoteSeventhMinor,
        NoteSeventhMajor,
        NoteSeventhAugmented,
        NoteNinthMinor,
        NoteNinthMajor,
        NoteNinthAugmented,
        NoteEleventhPerfect,
        NoteEleventhAugmented,
        NoteThirteenthMinor,
        NoteThirteenthMajor
    }
}